### ISSUE TITLE
Is there a way to use Swift-Kuery to get the last inserted ID?

### ISSUE THREAD

**Issue by jkingoliver** [IBM-Swift/Swift-Kuery#10]
This is the syntax for PosgreSQL:

```sql
INSERT INTO persons (lastname,firstname) VALUES ('Smith', 'John') RETURNING id;
``` 

For reference, there are a couple other approaches possible:

http://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id

**Comment by matthewcheok** [comment]
Just noticed this feature is missing in the current source. Any idea why?

**Comment by ianpartridge** [comment]
Hi @matthewcheok.

This was removed in https://github.com/IBM-Swift/Swift-Kuery/issues/25 because it's a Postgres specific feature, and Kuery aims to be a general abstraction across SQL databases.

You can use the `Insert.suffix(_:)` API at https://github.com/IBM-Swift/Swift-Kuery/blob/master/Sources/SwiftKuery/Insert.swift#L174 to add a `RETURNING id;` to your query instead.
