### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by isabellyfd** [IBM-Swift/Swift-Kuery#104]
I'm trying to update a local postgreSQL database entity with the following command: 
```swift
func update(_ activityId: Int, with likesCount: Int, and totalFeedback: Int){     
    let updateRating = Update(self.activities, set: [(activities.likeCount, likesCount), (activities.totalFeedback, totalFeedback)],where: (activities.id == activityId))
    self.connection.execute(query: updateRating) { (queryResult) in
        print(queryResult)
        print(queryResult.success)
    }
} 
```
But I can get to change these two properties in my database. I have tried to create a raw query through the API, but that didn't work was well.

**Comment by kilnerm** [comment]
Hi @isabellyfd, Did you ever solve your issue?

I have written a short testcase based on your sample code above and everything seems to work fine with me (of course it has been a while since the issue was opened). Let me know if you still need any assistance and I can give you my sample code for reference.

**Comment by isabellyfd** [comment]
I'd solved the issue. Thanks!

2018-09-04 9:08 GMT-03:00 kilnerm <notifications@github.com>:

**Comment by kilnerm** [comment]
Thanks for letting me know. Marking this as closed.
