### ISSUE TITLE
ConnectionPool doesn't discard dead connections

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Swift-Kuery#120]
I'd expect that when a connection is closed the ConnectionPool will recycle it. Unfortunately, it appears that a dead connection will continue to be vended by the ConnectionPool. I don't see any API to mark a connection as dead.

When using the PostgresQL connection adapter I've seen that sometimes the connections will die. This will happen when developing locally if I put my computer to sleep and wake it back up, for example. I don't know why it happens in production. Once this happens the server will be unable to do any database work without restarting.

**Comment by bridger** [comment]
@EnriqueL8, yeah that looks like it is the root cause of the issue.

It isn't a simple fix, though. If all the connections were to die at once (which is the common case), then the pool would be empty and subsequent calls to `getConnection()` would [return nil](https://github.com/IBM-Swift/Swift-Kuery/blob/master/Sources/SwiftKuery/ConnectionPool.swift#L124). The pool [only grows when you take the last item](https://github.com/IBM-Swift/Swift-Kuery/blob/master/Sources/SwiftKuery/ConnectionPool.swift#L129), it isn't able to grow if there are 0 items.

Even if the release() bug were fixed so that it properly removes the connection from the pool it would  be nice if this were done automatically somehow. Every time I query the database I have a bunch of boilerplate to check for errors already. Checking for a dead connection and calling `closeConnection()` will be yet another thing I need to remember every time I query the database. Maybe the connection could close itself after it receives an error?

**Comment by bridger** [comment]
Any update on this? It is one of the biggest sources of instability in my server app - once a connection goes bad there is no way to make the pool stop vending it. I've done some hacky workarounds, but that means I'm running a forked version which is a pain every time a new Swift version is released.

**Comment by ianpartridge** [comment]
@djones6 @ddunn2 @EnriqueL8 did we make any progress on this? IIRC one of you was looking at it!

**Comment by djones6** [comment]
@bridger Apologies, it seems that this was fixed but no reference was made to this issue.
This was fixed in a number of places:
- [Swift-Kuery `1.3.0`](https://github.com/IBM-Swift/Swift-Kuery/releases/tag/1.3.0): ConnectionPool no longer vends dead connections (#123 and #127), and can recover from being empty (#128) - such as in the case where the DB is temporarily not contactable.
- [Swift-Kuery-PostgreSQL `1.1.4`](https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL/releases/tag/1.1.4): use `PQstatus` to check connection state in `isConnected` ([#49](https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL/pull/49))

Unfortunately there are a couple of wrinkles that we do not have a solution for yet, which hopefully are not show-stoppers for you:

### Checking status of a Postgres connection
The way that `PQstatus` is implemented in libpq means that Postgres connections don't get flagged as disconnected until a query is attempted.  This means each must fail to execute a query before it will be thrown away and replaced.

For example, in the following scenario:
- A connection pool is set up with 2 connections
- Successful queries are made
- Database connection lost (network down, machine went to sleep, DB down)
- (no further query attempts)
- DB connection restored

... the next 2 queries will fail, because the ConnectionPool will vend (apparently) valid connections, but libpq will then flag them as failed.  They'll be be replaced the next time the ConnectionPool returns a connection, with a working one (assuming the DB is now reachable again).

### Connection generation failure
At the moment, the API for generating a new connection is synchronous, but the `connect()` function is asynchronous.  This means it's awkward to check whether a connection is 'connected' before returning it from the generator (effectively requiring the user to write a synchronous wrapper to connect()).  The generator needs be able to fail (ie. return nil) in order to prevent the ConnectionPool vending new (but dead) connections in the event of a DB outage.

We can still recover when the DB becomes reachable again, but we have to iterate through all the bad connections in the pool (with a query failure on each in the case of Postgres) before we've replaced them all with good ones.

**Comment by bridger** [comment]
This is awesome news! (Sorry I missed the message for a couple weeks)

I updated to the latest Kuery and it is working for me great. The caveats you mentioned are pretty reasonable.

Thank you for fixing these bugs 🤩 This will improve my server stability and it is also great to run a non-forked version of the code.
