### ISSUE TITLE
SQLite syntax error

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Swift-Kuery#23]
```
=======SELECT UPPER(tableSelectOSX.a) AS case, tableSelectOSX.b FROM tableSelectOSX WHERE tableSelectOSX.a BETWEEN 'apra' AND 'aprt'=======
Error in query:  near "case": syntax error
```

**Comment by irar2** [comment]
Looks like SQLite gets confused by 'case', please change the test to some other string

**Comment by ianpartridge** [comment]
Should Kuery prevent building this SQL, because of the potential syntax error?

**Comment by irar2** [comment]
It works with quotes, i.e.
```sql
SELECT UPPER(tableSelectOSX.a) AS "case"...
```
I will add quotes for all the aliases.

**Comment by irar2** [comment]
It turned out to be tricky. If we want to avoid such errors, we need to add quotes to all the names, not just to the aliases. But the problem is that a name with quotes is not always equal to the name without quotes (PostgreSQL lowercases everything without quotes, so CREATE TABLE X will create a table named x, while CREATE TABLE "X" will create a table X.

Another possible solution is to list all the keywords (db depending) and add quotes around them, but this seems to be too much. 

I think we can just change the test.

**Comment by ianpartridge** [comment]
OK. Can you change the PostgreSQL test too? I'd like to keep the tests as closely in sync as possible.

**Comment by irar2** [comment]
Changed it to "upper case" (and this helped to discover a bug - I forgot to add quotation marks around names of column expressions).

**Comment by irar2** [comment]
Fixed
