### ISSUE TITLE
Casting result to Int vs Int32

### ISSUE THREAD

**Issue by damir-sirola** [IBM-Swift/Swift-Kuery#76]
Hi,

thank you for the wonderful library but I have a question regarding casting result to Int and Int32.

I have the following table definition:
```
import SwiftKuery
import SwiftKueryPostgreSQL

class Tokens: Table {
    let tableName = "tokens"
    let id = Column("id", String.self, primaryKey: true, notNull: true, unique: true)
    let userId = Column("userId", String.self, notNull: true)
    let createdAt = Column("createdAt", Int64.self, notNull: true)
    var updatedAt = Column("updatedAt", Int64.self, notNull: true)
    var idle = Column("idle", Int.self, notNull: true)
}
```

and I execute this query

```
        let getTokenById =
            Select(fields: [tokens.id, tokens.userId, tokens.createdAt, tokens.updatedAt, tokens.idle], from: [tokens])
                .where(tokens.id == id)
                .limit(to: 1)
        connection.execute(query: getTokenById) { result in
            if let row = result.asRows?.first {
                guard let id = row["id"] as? String,
                        let userId = row["userid"] as? String,
                        let createdAt = row["createdat"] as? Int64,
                        let updatedAt = row["updatedat"] as? Int64,
                        let idle = row["idle"] as? Int else {
                    return
                }
                // Use values defined above
            }
        }
```

Now the problem is that assignment to `idle` variable fails. If I cast to Int32 everything works fine
(`let idle = row["idle"] as? Int32 else {` - this one works fine)

I just want to know if the problem is in Swift, Kuery or I'm doing something wrong?

**Comment by irar2** [comment]
The problem is that we map both Int and Int32 to the same Postgres type - "integer". When we get "integer" results we map them to Swift Int32, and  at this point (in PostgreSQLResultFetcher) we don't know the "Kuery type" of the column, only the postgres/libpq type, which is int4 in this case.

Also Int in Swift can be 32 bits or 64 bits depending on the platform.

So, we are considering to remove Int from SQLDataTypes, and just use Int16, Int32, Int64 for integers.

**Comment by damir-sirola** [comment]
Thank you for quick response.
